### ISSUE TITLE
Need  documentation for dev build

### ISSUE THREAD

**Issue by readroberts** [typemytype/booleanOperations#12]
I cannot currently build either the dev or non-dev version, under Mac OSX. I've seen some comments which make me think that this is an Xcode vs OSX version issue, but rather than spend more time on chasing this down, I'd like to see you document at known versions of the compiler + os + Cython that work.

**Comment by anthrotype** [comment]
could you please provide more info as to what build errors you are getting?
I've tested it on Yosemite 10.10 with latest Xcode 7.1 and Cython 0.23.4 and it seems to be working.

**Comment by anthrotype** [comment]
Travis CI runs on OS X 10.9 Mavericks and the build passes fine.
http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by readroberts** [comment]
This is a not an issue after all. I am still using Xcode 4.5, and there are documented issues with the lipo tool under OX 10.10 and later. I can compile this just fine with newer versions of Xcode, as well as under Linux and Windows.
