### ISSUE TITLE
clipperScale

### ISSUE THREAD

**Issue by behdad** [typemytype/booleanOperations#21]
It's currently set to 100000.  This is not ideal.  It has more rounding error that it has to.  For example, using this scale, 18 / 3 will NOT result in 6:
```
>>> s = 100000
>>> ((18 * s) // 3 * (1./s))
6.000000000000001
>>> ((18 * s) // 3 * (1./s)) == 6
False
```

Whereas if you use a power of two, rounding will be minimized.  I suggest 1<<16, to be close to your existing number.

```
>>> s = 1<<16
>>> ((18 * s) // 3 * (1./s))
6.0
>>> ((18 * s) // 3 * (1./s)) == 6
True
```

**Comment by typemytype** [comment]
oh, great, did you encounter an issues related to a false negative? 

```python
s = 1<<17
os = 100000

sc = 0
osc = 0
for i in range(1, 1000):
    for j in range(1, 1000):
        c =  i // float(j)
        if not c == ((i * s) // j * (1./s)):
            sc += 1
        if not c == ((i * os) // j * (1./os)):
            osc += 1

        
print "false result for %s: %s" % (s, sc)
print "false result for %s: %s" % (os, osc)
```

```
false result for 131072: 990948
false result for 100000: 994055
```

will change it but maybe one power higher.
thanks

**Comment by typemytype** [comment]
changed here https://github.com/typemytype/booleanOperations/commit/ebeaf6ba940dbfeda25b232a065f0cabf8ec9a8f

**Comment by behdad** [comment]
> oh, great, did you encounter an issues related to a false negative?

No.  I was just reading the code and noticed this can be improved.
