### ISSUE TITLE
Static library?

### ISSUE THREAD

**Issue by adrientetar** [typemytype/booleanOperations#23]
It would be nice to have possibility to compile booleanOperations as static lib, which makes things easier for dist.

cc @anthrotype

**Comment by anthrotype** [comment]
AFAIK Python extension modules must be shared libraries (the interpreter dynamically loads them at runtime).
booleanOperation is a package that mixes Python and C++. You can compile a static library of the C++ clipper module, but you want be able to use it from Python.
What's the problem with the shared library? What are you trying to statically link it with?

**Comment by adrientetar** [comment]
I am building with pyqtdeploy and Qt qmake and I get an ImportError even though I include the .so in the package along with the source files... maybe I need to investigate further.

**Comment by typemytype** [comment]
Embedding is working fine for years already with py2app, I assume it is not so different how packages get zipped and embedded into an app

**Comment by adrientetar** [comment]
Closing until I find out more.
