### ISSUE TITLE
cppWrapper/setup.py is executable, but misses #! header for python

### ISSUE THREAD

**Issue by roozbehp** [typemytype/booleanOperations#4]
cppWrapper/setup.py is executable, but misses #! header for python

As a result, people like me may try to run it as ./setup.py build and get weird errors because it will be run by bash or some other shell.

**Comment by roozbehp** [comment]
@jamesgk FYI.

**Comment by typemytype** [comment]
fixed, thanks

https://github.com/typemytype/booleanOperations/commit/24e1b044ad5cc514a28f596dfac32b7cbd8dcdad
