### ISSUE TITLE
Unreachable, unused code

### ISSUE THREAD

**Issue by rsms** [typemytype/booleanOperations#45]
The function `reCurveFromInputContourSegments ` in flatten.py is a noop with an unreachable body (first statement is `return`):

https://github.com/typemytype/booleanOperations/blob/e65175badaa304578087cf921724fbc53676cc52/Lib/booleanOperations/flatten.py#L560-L563

Used by `BooleanOperationManager` at:

https://github.com/typemytype/booleanOperations/blob/e65175badaa304578087cf921724fbc53676cc52/Lib/booleanOperations/booleanOperationManager.py#L89-L90

Seems that removing the function and removing the for-loop (that currently does nothing) from `BooleanOperationManager` would be better than to keep this dead code around.

Alternatively, it's a bug and the early `return` statement was inserted during debugging and accidentally committed.

**Comment by anthrotype** [comment]
yep, dead code. I think it was intentionally disabled.
@typemytype?
