### ISSUE TITLE
Is BooleanOperations derived from Clipper?

### ISSUE THREAD

**Issue by mavit** [typemytype/booleanOperations#47]
We’re [looking to package this library as a part of Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1440992).  Part of the packaging process includes checking that the licence allows us to redistribute the software.

Now, `README.rst` states:

> Boolean operations on paths based on a super fast polygon clipper library by Angus Johnson

What exactly is meant by this?  I ask because BooleanOperations is under the MIT licence, but Clipper is under the Boost Software License, which states:

> The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software

It seems that there could be a problem here, if BooleanOperations is a derivative of Clipper.

**Comment by anthrotype** [comment]
@athos-ribeiro is correct. BooleanOperations _uses_ pyclipper which in turns _uses_ the C++ Clipper library. It does not modify it so it's not a derivative work.
I'll change the wording of the README to clarify that, thanks.
