### ISSUE TITLE
Spurious points may remain from curves with zero-handles

### ISSUE THREAD

**Issue by madig** [typemytype/booleanOperations#53]
A curve with zero handles may leave behind spurious points.

1. Get [test.ufo.zip](https://github.com/typemytype/booleanOperations/files/2788454/test.ufo.zip)
2. `fontmake -u test.ufo -o ttf`

![image](https://user-images.githubusercontent.com/380829/51625895-43efe100-1f36-11e9-8715-cdf1f1abbe2c.png)

The same happens with pathops, btw.

**Comment by typemytype** [comment]
this seems to be normal behaviour: your off curve is overlapping the line segment, thus makes a very tiny hole...
