### ISSUE TITLE
colinear overlaps not detected

### ISSUE THREAD

**Issue by gferreira** [typemytype/booleanOperations#54]
continuing from [hasOverlap() does not detect all overlaps? (RoboFont Forum)](https://forum.robofont.com/topic/631/hasoverlap-does-not-detect-all-overlaps/5)

it seems the problem can be generalised to *colinear straight segments in different contours*. here are some examples with other shapes (red circles show detected overlaps):

![Screen Shot 2019-04-29 at 13 50 41](https://user-images.githubusercontent.com/62717/56912597-f7acc380-6a85-11e9-95ad-8f3358b59329.png)

![Screen Shot 2019-04-29 at 13 50 37](https://user-images.githubusercontent.com/62717/56912596-f7142d00-6a85-11e9-9094-59a376d8966f.png)

some points appear/disappear when the objects are rotated:

![Screen Shot 2019-04-29 at 13 50 28](https://user-images.githubusercontent.com/62717/56912595-f7142d00-6a85-11e9-8deb-d5cafe3b5907.png)

here’s a helper to visualize overlaps while editing a glyph:

```python
from vanilla import *
from defconAppKit.windows.baseWindow import BaseWindowController
from mojo.events import addObserver, removeObserver
from mojo.UI import UpdateCurrentGlyphView
from mojo.drawingTools import *

class ShowOverlaps(BaseWindowController):

    def __init__(self):
        self.w = FloatingWindow((130, 40))
        self.w.draw = CheckBox((10, 10, -10, 20), 'show overlaps', value=True, callback=self.updateViewCallback)
        addObserver(self, "drawBackgroundCallback", "drawBackground")
        self.setUpBaseWindowBehavior()
        self.w.open()

    def windowCloseCallback(self, sender):
        removeObserver(self, 'drawBackground')
        super(ShowOverlaps, self).windowCloseCallback(sender)

    def updateViewCallback(self, sender):
        UpdateCurrentGlyphView()

    def drawBackgroundCallback(self, info):
        if not self.w.draw.get():
            return
        g = info["glyph"]
        pts = g.hasOverlap()
        if not len(pts):
            return
        r = 20
        save()
        fill(None)
        stroke(1, 0, 0)
        strokeWidth(10)
        for x, y in pts:
            oval(x-r, y-r, r*2, r*2)
        restore()
        UpdateCurrentGlyphView()

ShowOverlaps()
```

thanks in advance for looking into it!

**Comment by typemytype** [comment]
can the glif xml be posted? 

thanks!!

**Comment by gferreira** [comment]
sure, here are some rects :) [testOverlaps.ufo.zip](https://github.com/typemytype/booleanOperations/files/3128446/testOverlaps.ufo.zip) thx

**Comment by typemytype** [comment]
Oh yeah, `getIntersections()` is just returning all new points... in most of those cases there is no **new**  point as the intersection is on top of an existing point...

see https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/booleanOperationManager.py#L133
