### ISSUE TITLE
Union produces different contour order depending on platform

### ISSUE THREAD

**Issue by madig** [typemytype/booleanOperations#55]
Stumbled over this because fonts build on our build server (running Linux) produce differently ordered contours for a specific glyph which broke hinting. Can reproduce with two glyphs from Noto Sans Regular ([NotoSansTest.ufo.zip](https://github.com/typemytype/booleanOperations/files/3798589/NotoSansTest.ufo.zip)). Running the following script on Linux and Windows will produce differently ordered contours:

```Python
import sys

import booleanOperations
import ufoLib2

u = ufoLib2.Font.open("NotoSansTest.ufo")

for g in u:
    if not g.contours:
        continue

    cs = [c for c in g.contours]
    g.clearContours()
    p = g.getPointPen()
    booleanOperations.union(cs, p)

if sys.platform == "win32":
    u.save("test-win.ufo")
else:
    u.save("test-lin.ufo")
```

Still drilling down to where this happens.

**Comment by madig** [comment]
It happens inside `clipExecute()`. The input parameters are the same, but the output `resultContours` are ordered differently on Windows and Linux.

**Comment by madig** [comment]
Here's a reproducer driving pyclipper directly: https://gist.github.com/madig/998ec05ef8a496f984aaa86aeceda6fc.

**Comment by anthrotype** [comment]
I suggest you open the bug on pyclipper repository, maybe other non-font users can help

**Comment by madig** [comment]
Filed upstream at https://sourceforge.net/p/polyclipping/bugs/195.

**Comment by madig** [comment]
Oh well. angusj responded there and said it's just how the algorithm works. Guess I have to write that ufo2ft filter.

**Comment by madig** [comment]
Optional ufo2ft filter implemented in https://github.com/googlefonts/ufo2ft/pull/345.
